apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./external-snapshotter.yaml
  - ./csi-powerstore-namespace.yaml
  - ./csi-powerstore-secret.yaml
  - ./csi-powerstore-2.5.0.yaml
  - ./storageclass-standard-non-default.yaml
  - ./storageclass-powerstore-topology.yaml
  - ./volumesnapshotclass-powerstore.yaml
  - ./metallb.yaml
  - ./metallb-config.yaml
  - ./nginx-ingress-controller.yaml
  - ./cluster-autoscaler.yaml
  - ./rabbitmq-operator.yaml
  - ./ppdm-rbac.yaml
patches:
  - path: ./patches/patch-deployment.yaml
    target:
      kind: Deployment
  - path: ./patches/patch-daemonset.yaml
    target:
      kind: DaemonSet
  - path: ./patches/patch-nginx-ingress-controller.yaml
    target:
      group: core
      version: v1
      kind: Service
      name: ingress-nginx-controller
      namespace: ingress-nginx
  - path: ./patches/patch-metallb-config.yaml
    target:
      group: metallb.io
      version: v1beta1
      kind: IPAddressPool
      name: first-pool
      namespace: metallb-system
